### ISSUE TITLE
Needs a 404 page

### ISSUE THREAD

**Issue by riordan** [BadIdeaFactory/biffud.com#1]

**Comment by chriszs** [comment]
See @Laurian's suggestion in #33

**Comment by slifty** [comment]
We have a basic 404 page now which plays Ian's song; there is tons more to add.  One thought:

1) Have the text change over time, as the user is listening, ideally with a variety of possible scripts.
2) Add a button / modal for mobile users to click of "Alick this to see our 404 page" since music won't auto play without user interaction on mobile.

**Comment by chriszs** [comment]
Consider adding additional issues with those enhancements.
